SRCS_GUI-$(QT5) = gui/qt/mainwindow.cpp \
             gui/qt/moc_mainwindow.cpp \
             gui/qt/qrc_mainwindow.cpp \
             gui/qt/DictIndexModel.cpp \
             gui/qt/moc_DictIndexModel.cpp \
             gui/qt/VBookModel.cpp \
             gui/qt/moc_VBookModel.cpp \
             gui/qt/QtMessager.cpp \
             gui/qt/moc_QtMessager.cpp

